\input texinfo   @c -*-texinfo-*-

@c %**start of header
@setfilename secnote.info
@settitle secnote
@afourpaper
@documentencoding UTF-8
@documentlanguage en
@finalout
@c %**end of header


@copying
This manual is for secnote.

Copyright @copyright{} 2013 Mattias Andrée

@quotation
Copying and distribution of this file, with or without modification,
are permitted in any medium without royalty provided the copyright
notice and this notice are preserved.  This file is offered as-is,
without any warranty.

(GNU All Permissive License)
@end quotation
@end copying


@ifnottex
@node Top
@top secnote
@insertcopying
@end ifnottex

@titlepage
@title secnote
@subtitle Encrypted note taking
@author Mattias Andrée, maandree@@member.fsf.org
@page
@vskip 0pt plus 1filll
@insertcopying
@page
@*@*
@center{`...'}
@end titlepage

@contents


@menu
* License of secnote::               Summary of the license of the program
@end menu



@node License of secnote
@appendix License of secnote

@flushleft
secnote – Encrypted note taking

Copyright © 2013  Mattias Andrée (maandree@@member.fsf.org)

Copying and distribution of this file, with or without modification,
are permitted in any medium without royalty provided the copyright
notice and this notice are preserved.  This file is offered as-is,
without any warranty.

(GNU All Permissive License)
@end flushleft

@bye

